name: Pylint
permissions:
  contents: read

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: false
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install dependencies
      run: |
        poetry install
    - name: Analysing the code with pylint
      run: |
        poetry run pylint $(git ls-files '*.py')
